import type {Metadata} from 'next';

import React from 'react';

import {Plus_Jakarta_Sans} from 'next/font/google';

import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({subsets: ['latin']});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Lidia',
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang={'en'}>
    <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
